pipeline {
    agent {
            docker {
                image 'maven:3.9-eclipse-temurin-21'
                args '-v /root/.m2:/root/.m2'
            }
        }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build with Maven') {
            agent {
                            docker {
                                image 'maven:3.9-eclipse-temurin-21'
                                args '-v /root/.m2:/root/.m2'
                                reuseNode true
                            }
                        }
                        steps {
                            sh 'mvn clean package -DskipTests'
                        }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    sh 'docker build -t myapp:${BUILD_NUMBER} .'
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                sh 'kubectl apply -f k8s-deployment.yaml'
            }
        }
    }

    post {
        success {
            echo 'Pipeline succeeded!'
        }
        failure {
            echo 'Pipeline failed!'
        }
    }
}